import React from "react";
import { WorkflowDesc } from "../components/WorflowDesc";

const About: React.FC = () => {
  return (
    <div className="text-gray-300 my-6">
      <h2 className="text-3xl font-bold mb-6 text-center">About Image of the Day</h2>
      <p className="mb-4">
        Welcome to <b>Image of the Day</b>! This project is a simple experiment in generating daily
        AI-created images inspired by random news headlines.
      </p>
      <p className="mb-4">Each day, our system performs three automatic steps:</p>
      <ul className="list-disc list-inside ml-4 space-y-2 mb-10">
        <li>We fetch 50 current <i>news headlines</i> using RSS feeds.</li>
        <li>We select 5 random headlines from the fetched list.</li>
        <li>We use it to create an AI-optimized "artistic prompt".</li>
        <li>
          Finally, we use that generated prompt to create a unique piece of **digital art**
          generated by AI.
        </li>
      </ul>

      <WorkflowDesc />
    </div>
  );
};

export default About;
